version: '3.1'
services:
  backend:
    # image: maven:3.6.3-jdk-8
    image: maven:3.8.7-openjdk-18
    command: mvn spring-boot:run  # mvn clean install # &&
    # command:  mvn clean install # &&
    ports:
      - 8088:8080
    depends_on:
     - database
    volumes:
      - .:/usr/src/mymaven:rw
    working_dir: /usr/src/mymaven
  database:
    container_name: shoes_database
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
        MYSQL_DATABASE: 'shoes'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'shoes_root'
        # You can use whatever password you like
        MYSQL_PASSWORD: 'toor'
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      - 3307:3306
